[package]
name = "rs_quickjs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
rs_quickjs = []

[dependencies]
lazy_static = "1.5.0"
bitflags = "2.10.0"

[build-dependencies]
bindgen = "0.72.1"
