[package]
name = "rs_core_audio"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.10.0"
log = "0.4.29"
dasp = { version = "0.11.0", features = ["all"] }

[dev-dependencies]
log = "0.4.29"
env_logger = "0.11.8"
